apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-blue
  labels:
    app: messaging-app
    version: blue
spec:
  replicas: 2  # Reduced replicas for testing
  selector:
    matchLabels:
      app: messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: messaging-app
        version: blue
    spec:
      containers:
      - name: messaging-app
        image: nginx:1.22  # Updated to version 1.22 (represents v2.0)
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "blue-v2.0"  # Updated to v2.0
        # Simplified health checks
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        # Add a custom index.html to identify the version
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: messaging-app-blue-content
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-app-blue-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Messaging App - Blue Version</title>
        <style>
            body { background-color: #e3f2fd; color: #0d47a1; font-family: Arial, sans-serif; text-align: center; padding: 50px; }
            h1 { color: #1976d2; }
            .version { background-color: #1976d2; color: white; padding: 10px; border-radius: 5px; display: inline-block; margin: 10px; }
        </style>
    </head>
    <body>
        <h1>Messaging App - Blue Version</h1>
        <div class="version">v2.0 - Rolling Update Success!</div>
        <p>This is the updated blue deployment</p>
        <p>Status: Active</p>
        <p>Updated: $(date)</p>
    </body>
    </html>