apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-blue
  labels:
    app: messaging-app
    version: blue
spec:
  replicas: 2  # Reduced replicas for testing
  selector:
    matchLabels:
      app: messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: messaging-app
        version: blue
    spec:
      containers:
      - name: messaging-app
        image: nginx:1.21  # Using nginx as a simple test instead of custom Django image
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "blue-v1.0"
        # Simplified health checks
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        # Add a custom index.html to identify the version
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: messaging-app-blue-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-app-blue-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Messaging App - Blue Version</title>
        <style>
            body { background-color: #e3f2fd; color: #0d47a1; font-family: Arial, sans-serif; text-align: center; padding: 50px; }
            h1 { color: #1976d2; }
        </style>
    </head>
    <body>
        <h1>Messaging App - Blue Version (v1.0)</h1>
        <p>This is the stable blue deployment</p>
        <p>Status: Active</p>
    </body>
    </html>